<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyName>MouseCursorSupporter</AssemblyName>
    <Product>マウスカーソル自動切替</Product>
    <Company>ryokamur</Company>
    <Version>0.3.0</Version>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

</Project>